### ISSUE TITLE
Altcoin data

### ISSUE THREAD

**Issue by bensendk** [DiscoTiger/SellBot#2]
How Many coins Can you get info from?? I have for example Trier “$info iota” and others but it dosent answer. Can i do something to add more coins to get info from.

Regards
Benjamin bøg

**Comment by DiscoTiger** [comment]
Hey, sorry I didn't see your issue. Iota actually does work but that's not the currency symbol for that coin... For some reason it's MIOTA. 
Sellbot pulls from coinmarketcap.com using the ticker symbol, not the coin name.
